import { StyleSheet } from 'react-native';

import { ALTASAI_COLORS } from '../../../theme/colors';
import { ALTASAI_SPACING } from '../../../theme/spacing';
import { ALTASAI_TYPOGRAPHY } from '../../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ALTASAI_COLORS.background.primary,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: ALTASAI_SPACING[5],
    paddingTop: ALTASAI_SPACING[3],
    paddingBottom: ALTASAI_SPACING[4],
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(5, 8, 12, 0.72)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ALTASAI_SPACING[3],
    flex: 1,
  },
  headerCopy: {
    flex: 1,
  },
  avatarFrame: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: ALTASAI_COLORS.intelligence.field,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.accent,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  headerEyebrow: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.accent.bright,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    letterSpacing: 1,
  },
  headerTitle: {
    fontSize: ALTASAI_TYPOGRAPHY.size['2xl'],
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.text.primary,
    letterSpacing: 0,
  },
  headerTaskLine: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.text.secondary,
    marginTop: 1,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ALTASAI_SPACING[2],
    paddingHorizontal: ALTASAI_SPACING[3],
    paddingVertical: ALTASAI_SPACING[2],
    borderRadius: 999,
    backgroundColor: 'rgba(16, 185, 129, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: ALTASAI_COLORS.success.primary,
  },
  statusDotWarning: {
    backgroundColor: ALTASAI_COLORS.warning.light,
  },
  statusText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.success.light,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
  },
  statusTextWarning: {
    color: ALTASAI_COLORS.warning.light,
  },
  chatContainer: {
    flex: 1,
  },
  messagesList: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: ALTASAI_SPACING[4],
    paddingTop: ALTASAI_SPACING[3],
  },
  briefPanel: {
    marginBottom: ALTASAI_SPACING[5],
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(115, 240, 203, 0.18)',
  },
  briefGradient: {
    padding: ALTASAI_SPACING[5],
  },
  briefTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: ALTASAI_SPACING[3],
  },
  briefLabel: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.accent.bright,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    letterSpacing: 1,
  },
  modeDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  briefTitle: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xl,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.text.primary,
    marginBottom: ALTASAI_SPACING[2],
  },
  briefText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    color: ALTASAI_COLORS.text.secondary,
    lineHeight: 20,
  },
  messageBubbleRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: ALTASAI_SPACING[4],
    gap: ALTASAI_SPACING[2],
  },
  messageRowRight: {
    justifyContent: 'flex-end',
  },
  messageAvatar: {
    width: 30,
    height: 30,
    borderRadius: 9,
    backgroundColor: ALTASAI_COLORS.background.elevated,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.accent,
    overflow: 'hidden',
  },
  messageAvatarImage: {
    width: '100%',
    height: '100%',
  },
  messageBubble: {
    maxWidth: '84%',
    borderRadius: 8,
    paddingHorizontal: ALTASAI_SPACING[3],
    paddingVertical: ALTASAI_SPACING[3],
  },
  aiBubbleWithAvatar: {
    maxWidth: '78%',
  },
  userBubble: {
    backgroundColor: ALTASAI_COLORS.accent.primary,
    borderBottomRightRadius: 2,
  },
  aiBubble: {
    backgroundColor: 'rgba(20, 25, 34, 0.86)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
    borderBottomLeftRadius: 2,
  },
  offlineBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: ALTASAI_SPACING[2],
    marginBottom: ALTASAI_SPACING[2],
    paddingHorizontal: ALTASAI_SPACING[2],
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.24)',
    backgroundColor: 'rgba(245, 158, 11, 0.10)',
  },
  offlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: ALTASAI_COLORS.warning.light,
  },
  offlineText: {
    color: ALTASAI_COLORS.warning.light,
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
  },
  messageText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    color: ALTASAI_COLORS.text.primary,
    lineHeight: 21,
    letterSpacing: 0,
  },
  userMessageText: {
    color: '#FFFFFF',
  },
  messageMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: ALTASAI_SPACING[2],
  },
  messageTime: {
    fontSize: 10,
    color: ALTASAI_COLORS.text.tertiary,
  },
  userMessageTime: {
    color: 'rgba(255, 255, 255, 0.72)',
  },
  shareButton: {
    fontSize: 10,
    color: ALTASAI_COLORS.accent.bright,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
  },
  messageAvatarSpeaking: {
    borderColor: ALTASAI_COLORS.accent.bright,
    borderWidth: 2,
  },
  speakingRing: {
    position: 'absolute',
    top: -3,
    left: -3,
    right: -3,
    bottom: -3,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: ALTASAI_COLORS.accent.bright,
    opacity: 0.5,
  },
  typingContainer: {
    marginBottom: ALTASAI_SPACING[4],
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ALTASAI_SPACING[3],
    backgroundColor: 'rgba(20, 25, 34, 0.90)',
    borderRadius: 8,
    paddingHorizontal: ALTASAI_SPACING[4],
    paddingVertical: ALTASAI_SPACING[3],
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  typingBar: {
    width: 34,
    height: 4,
    borderRadius: 2,
    backgroundColor: ALTASAI_COLORS.accent.bright,
  },
  typingText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    color: ALTASAI_COLORS.text.secondary,
  },
  quickResponses: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: ALTASAI_SPACING[2],
    backgroundColor: 'rgba(5, 8, 12, 0.74)',
  },
  quickResponsesContent: {
    paddingHorizontal: ALTASAI_SPACING[4],
    gap: ALTASAI_SPACING[2],
    alignItems: 'center',
  },
  quickResponseButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 999,
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: ALTASAI_SPACING[3],
    paddingVertical: ALTASAI_SPACING[2],
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  quickResponseText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.text.secondary,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
    lineHeight: 16,
  },
  inputContainer: {
    paddingHorizontal: ALTASAI_SPACING[4],
    paddingTop: ALTASAI_SPACING[2],
    paddingBottom: ALTASAI_SPACING[3],
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(5, 8, 12, 0.86)',
  },
  inputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ALTASAI_SPACING[2],
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.20)',
    borderRadius: 8,
    paddingLeft: ALTASAI_SPACING[3],
    paddingRight: ALTASAI_SPACING[2],
    paddingVertical: ALTASAI_SPACING[1],
  },
  textInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 104,
    paddingVertical: ALTASAI_SPACING[2],
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    lineHeight: 20,
    color: ALTASAI_COLORS.text.primary,
    textAlignVertical: 'center',
    letterSpacing: 0,
  },
  sendButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  sendButtonActive: {
    backgroundColor: ALTASAI_COLORS.accent.primary,
    borderColor: ALTASAI_COLORS.accent.bright,
  },
  bottomSpacer: {
    height: ALTASAI_SPACING[4],
  },
  actionsContainer: {
    marginTop: ALTASAI_SPACING[3],
    gap: ALTASAI_SPACING[2],
  },
  actionChip: {
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: ALTASAI_SPACING[3],
    paddingVertical: ALTASAI_SPACING[2],
  },
  actionChipLabel: {
    fontSize: 9,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.accent.bright,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  actionChipTitle: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.text.secondary,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
  },
});
