export const ROUTES = {
  ROOT: '/',
  AUTH: {
    WELCOME: '/(auth)/welcome',
    LOGIN: '/(auth)/login',
    REGISTER: '/(auth)/register',
    ONBOARDING: '/(auth)/onboarding',
  },
  MAIN: {
    HOME: '/(main)',
    TASKS: '/(main)/tasks',
    TASK_DETAIL: '/(main)/task-detail',
    FOCUS: '/(main)/focus',
    GOALS: '/(main)/goals',
    MENTOR: '/(main)/mentor',
    CORTEX: '/(main)/cortex',
    BEHAVIOR_TIMELINE: '/(main)/behavior-timeline',
    INTERVENTIONS: '/(main)/interventions',
    REPORTS: '/(main)/reports',
    DAILY_REPORT: '/(main)/daily-report',
    WEEKLY_REPORT: '/(main)/weekly-report',
    PROFILE: '/(main)/profile',
    ANALYTICS: '/(main)/analytics',
    KHATA: '/(main)/khata',
    ADD_EXPENSE: '/(main)/add-expense',
    EXPENSE_HISTORY: '/(main)/expense-history',
    LEDGER: '/(main)/ledger',
    BUDGET_INSIGHTS: '/(main)/budget-insights',
    SECURITY: '/(main)/security',
    SCAN_LINK: '/(main)/scan-link',
    DEVICE_SAFETY: '/(main)/device-safety',
    DIGITAL: '/(main)/digital',
    HEALTH: '/(main)/health',
    REFLECTION: '/(main)/reflection',
    NEWS: '/(main)/news',
  },
} as const;
