import { StyleSheet } from 'react-native';

import { ALTASAI_COLORS, ALTASAI_SPACING, ALTASAI_TYPOGRAPHY } from '../../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: ALTASAI_SPACING[5],
    paddingTop: ALTASAI_SPACING[4],
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ALTASAI_SPACING[4],
    marginBottom: ALTASAI_SPACING[5],
  },
  backButton: {
    minWidth: 64,
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ALTASAI_COLORS.background.elevated,
  },
  backText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
    color: ALTASAI_COLORS.accent.primary,
  },
  headerTitleWrap: {
    flex: 1,
  },
  eyebrow: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
    color: ALTASAI_COLORS.accent.primary,
    textTransform: 'uppercase',
    letterSpacing: 0,
    marginBottom: ALTASAI_SPACING[1],
  },
  title: {
    fontSize: ALTASAI_TYPOGRAPHY.size['3xl'],
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.text.primary,
  },
  searchWrap: {
    marginBottom: ALTASAI_SPACING[4],
  },
  searchInput: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.primary,
    backgroundColor: ALTASAI_COLORS.background.elevated,
    paddingHorizontal: ALTASAI_SPACING[4],
    color: ALTASAI_COLORS.text.primary,
    fontSize: ALTASAI_TYPOGRAPHY.size.base,
  },
  topicRow: {
    gap: ALTASAI_SPACING[2],
    paddingBottom: ALTASAI_SPACING[5],
  },
  topicChip: {
    minHeight: 36,
    paddingHorizontal: ALTASAI_SPACING[4],
    borderRadius: 18,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ALTASAI_COLORS.background.secondary,
  },
  topicChipActive: {
    backgroundColor: ALTASAI_COLORS.accent.primary,
    borderColor: ALTASAI_COLORS.accent.primary,
  },
  topicText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
    color: ALTASAI_COLORS.text.secondary,
  },
  topicTextActive: {
    color: '#FFFFFF',
  },
  featuredCard: {
    padding: ALTASAI_SPACING[5],
    marginBottom: ALTASAI_SPACING[6],
  },
  featuredMedia: {
    height: 148,
    borderRadius: 16,
    backgroundColor: ALTASAI_COLORS.background.tertiary,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: ALTASAI_SPACING[4],
  },
  featuredMediaText: {
    fontSize: ALTASAI_TYPOGRAPHY.size['2xl'],
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.accent.bright,
    letterSpacing: 0,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: ALTASAI_SPACING[3],
    marginBottom: ALTASAI_SPACING[2],
  },
  priority: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.accent.primary,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  metaText: {
    flexShrink: 1,
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.text.tertiary,
    textAlign: 'right',
  },
  featuredTitle: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xl,
    lineHeight: 27,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.text.primary,
    marginBottom: ALTASAI_SPACING[3],
  },
  summary: {
    fontSize: ALTASAI_TYPOGRAPHY.size.base,
    lineHeight: 22,
    color: ALTASAI_COLORS.text.secondary,
  },
  labNotice: {
    marginTop: ALTASAI_SPACING[4],
    padding: ALTASAI_SPACING[3],
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.primary,
    backgroundColor: ALTASAI_COLORS.surface.subtle,
  },
  labNoticeText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    lineHeight: 19,
    color: ALTASAI_COLORS.text.secondary,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: ALTASAI_SPACING[3],
    marginTop: ALTASAI_SPACING[4],
  },
  readTime: {
    flex: 1,
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.text.tertiary,
  },
  saveButton: {
    minHeight: 36,
    paddingHorizontal: ALTASAI_SPACING[4],
    borderRadius: 18,
    backgroundColor: ALTASAI_COLORS.background.secondary,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonCompact: {
    minHeight: 32,
    paddingHorizontal: ALTASAI_SPACING[3],
    borderRadius: 16,
    backgroundColor: ALTASAI_COLORS.background.secondary,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.semibold,
    color: ALTASAI_COLORS.accent.primary,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: ALTASAI_SPACING[3],
  },
  sectionTitle: {
    fontSize: ALTASAI_TYPOGRAPHY.size.lg,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.text.primary,
  },
  sectionCount: {
    fontSize: ALTASAI_TYPOGRAPHY.size.xs,
    color: ALTASAI_COLORS.text.tertiary,
  },
  feedCard: {
    flexDirection: 'row',
    gap: ALTASAI_SPACING[4],
    padding: ALTASAI_SPACING[4],
    borderRadius: 16,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.primary,
    backgroundColor: ALTASAI_COLORS.background.elevated,
    marginBottom: ALTASAI_SPACING[3],
  },
  feedCardPressed: {
    opacity: 0.75,
  },
  feedMarker: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: ALTASAI_COLORS.background.tertiary,
    borderWidth: 1,
    borderColor: ALTASAI_COLORS.border.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedMarkerText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.accent.primary,
  },
  feedBody: {
    flex: 1,
  },
  feedTitle: {
    fontSize: ALTASAI_TYPOGRAPHY.size.base,
    lineHeight: 21,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.text.primary,
    marginBottom: ALTASAI_SPACING[2],
  },
  feedSummary: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    lineHeight: 19,
    color: ALTASAI_COLORS.text.secondary,
  },
  emptyCard: {
    padding: ALTASAI_SPACING[5],
  },
  emptyTitle: {
    fontSize: ALTASAI_TYPOGRAPHY.size.lg,
    fontWeight: ALTASAI_TYPOGRAPHY.weight.bold,
    color: ALTASAI_COLORS.text.primary,
    marginBottom: ALTASAI_SPACING[2],
  },
  emptyText: {
    fontSize: ALTASAI_TYPOGRAPHY.size.sm,
    color: ALTASAI_COLORS.text.secondary,
  },
  bottomSpacer: {
    height: 100,
  },
});
